config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :restaurants, only: [:update, :edit, :destroy] do
      resources :reviews, only: [:update, :edit, :destroy]
    end
  end


  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [ :index, :new, :create ]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :restaurant, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
  validates :content, presence: true
end

app/controllers/admin/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def edit

  end

  def update

  end

  def destroy

  end

  def find
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:id, :content, :rating, :restaurant_id)
  end
end

app/controllers/admin/reviews_controller.rb
class ReviewsController < ApplicationController
  def edit

  end

  def update

  end

  def destroy

  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def restaurant_params
    params.require(:review).permit(:id, )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new()
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def find
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:id, :name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [:index, :new, :create]

  def index
    @reviews = Review.where(restaurant_id: @restaurant.id)
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.valid?
      @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:id, :content, :rating, :restaurant_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="wrapper">
  <div class="container">
    <ul class="list-group" style="list-style-type: none;">
      <% @restaurants.each do |r| %>
      <div class="row">
        <li class="btn btn-light">
          <%= link_to "#{r.name} (#{r.category}) | #{r.address} | #{r.phone_number}", restaurant_path(r.id) %>
          <%= link_to "Create new review", new_restaurant_review_path(r) %>
        </li>
      </div>
      <% end %>
    </ul>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for [@restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "add a restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<%= "#{@restaurant.name} (#{@restaurant.category}) | #{@restaurant.address} | #{@restaurant.phone_number}" %>
<br>


<% @restaurant.reviews.each do |review| %>
  <%= review.content %>
<% end %>
<%= link_to "Show reviews", restaurant_reviews_path(@restaurant) %>

app/views/reviews/index.html.erb
<%= link_to "Create new review", new_restaurant_review_path(@restaurant) %>

<ul>
  <% @reviews.each do |r| %>
  <li>
    <%= "#{r.content} | Stars: #{r.rating} for Restaurant: #{r.restaurant.name}" %>
  </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>